### ISSUE TITLE
Can't seem to turn off busylight after enabling it

### ISSUE THREAD

**Issue by Nederby** [gnaudio/jabra-node-sdk#12]
First off it is a pleasure to work with this SDK 👍But we have one issue we can't get to work.:

When on call we enable the busylight and disable it again after the call has ended, but it seems we can't turn it off after enabling it on the device. 

Version: `jabra-node-sdk 2.0.0-beta.3`
Modal: `Jabra Evolve 75`
NodeJS: `10.13`
Electron: `4.1.0`
```javascript
await device.setBusyLightStatusAsync(true); // <-- Turn on the busylight on the device - Works 🎉 
await device.setBusyLightStatusAsync(false); // <-- Does not seem to work 🤔 

await device.getBusyLightStatusAsync(); // <-- returns true 
```

**Comment by extmchristensen** [comment]
Thanks - we are trying to reproduce this issue without success so far - will try again tomorrow.

**Comment by extmchristensen** [comment]
Hi Nederby,
We have been unable to reproduce this behavior in our own tests. I assume we do not understand your exact scenario correctly. Can you add a small script that reproduce the exact behavior you get with comments about what we should do on the device at various steps ?
P.S. See [one of the example scripts](https://github.com/gnaudio/jabra-node-sdk/blob/master/nodesdk/src/example/example2.ts) for inspiration on how to create such a script.

**Comment by Nederby** [comment]
Thank @extmchristensen I found the issue. It was because we didn't fire the offhook event when call was ended. Sorry and thanks for the help 👍

**Comment by extmchristensen** [comment]
@Nederby Thanks for the update. I am very glad your issue was resolved.
