### ISSUE TITLE
What devices are supported with the new nodeJS v2. SDK  ?

### ISSUE THREAD

**Issue by Nederby** [gnaudio/jabra-node-sdk#14]
I can't find a list of supported devices on this new SDK. 

**The supported device on the old SDK was.:**  
> PRO 9470, PRO 9460, PRO 9450, Biz 2300, Motion Office, Evolve 65 USB, Biz 2400 II CC, PRO 930, PRO 935 (single and dual), PRO 925 (single and dual), Evolve 40 /80, Link 265, Evolve 30 ||, Evolve 20, Biz 1500, Biz 2400 II, Evolve 30, Link 260, Evolve 75
> Motion UC (Over BT)
> Link 360, Link 370
> Speak 410, Speak 510, Speak 710, Speak 810

Thanks in advance

**Comment by JabraDIME** [comment]
Here is the list of devices we expect to be supported by the production release of the nodeJS v2 SDK: 

* AudioCodes HRS 457
* DELL PRO STEREO HEADSET UC150
* DELL PRO STEREO HEADSET UC350
* HP UC Wired Headset V2
* Jabra BIZ 1100 Mono
* Jabra BIZ 1100 Stereo
* Jabra BIZ 1500 USB Duo
* Jabra BIZ 1500 USB Mono
* Jabra BIZ 2300 USB Duo
* Jabra BIZ 2300 USB Mono
* Jabra BIZ 2400 II CC USB Mono
* Jabra BIZ 2400 II CC USB Stereo
* Jabra BIZ 2400 II Duo
* Jabra BIZ 2400 II Mono
* Jabra BIZ 2400 II USB Duo BT
* Jabra BIZ 2400 II USB Mono BT
* Jabra BIZ 2400 II USB Mono CC
* Jabra BIZ 2400 USB
* Jabra BIZ 2400 USB Duo
* Jabra BIZ 2400 USB Mono
* Jabra DIAL 550
* Jabra Engage 50 Mono
* Jabra Engage 50 Stereo
* Jabra Engage 65 Convertible
* Jabra Engage 65 Mono
* Jabra Engage 65 Stereo
* Jabra Engage 75 Convertible
* Jabra Engage 75 Mono
* Jabra Engage 75 Stereo
* Jabra Evolve 20 Mono
* Jabra Evolve 20 Stereo
* Jabra Evolve 20SE Mono
* Jabra Evolve 20SE Stereo
* Jabra Evolve 30 II Mono
* Jabra Evolve 30 II Stereo
* Jabra Evolve 30 Mono
* Jabra Evolve 30 Stereo
* Jabra Evolve 40/80
* Jabra Evolve 65 Mono
* Jabra Evolve 65 Stereo
* Jabra Evolve 65e
* Jabra Evolve 65t
* Jabra Evolve 65t Cradle
* Jabra Evolve 75
* Jabra Evolve 75e
* Jabra Handset 450
* Jabra LINK 230
* Jabra LINK 260
* Jabra LINK 265
* Jabra LINK 280
* Jabra LINK 30
* Jabra LINK 32
* Jabra LINK 33
* Jabra LINK 360
* Jabra LINK 370
* Jabra LINK 43
* Jabra LINK 44
* Jabra LINK 850
* Jabra LINK 860
* Jabra LINK 950
* Jabra Motion Office
* Jabra Motion UC
* Jabra Pro 920
* Jabra Pro 925 Dual Connectivity
* Jabra Pro 925 Single Connectivity
* Jabra Pro 930
* Jabra Pro 935
* Jabra Pro 935 Single Connectivity
* Jabra Pro 9450
* Jabra Pro 9460
* Jabra Pro 9465/9470
* Jabra SPEAK 410
* Jabra SPEAK 450 Cisco
* Jabra SPEAK 510
* Jabra SPEAK 710 MS
* Jabra SPEAK 710 Teams
* Jabra SPEAK 710 UC
* Jabra SPEAK 810
* Jabra STEALTH UC
* Jabra SUPREME
* Jabra SUPREME UC
* Jabra UC VOICE 150a Duo
* Jabra UC VOICE 150a Duo MS
* Jabra UC VOICE 150a Mono
* Jabra UC VOICE 150a Mono MS
* Jabra UC VOICE 250a
* Jabra UC VOICE 250a MS
* Jabra UC VOICE 550a Duo
* Jabra UC VOICE 550a Duo MS
* Jabra UC VOICE 550a Mono
* Jabra UC VOICE 550a Mono MS
* Jabra UC VOICE 750a Duo
* Jabra UC VOICE 750a Duo MS
* Jabra UC VOICE 750a Mono
* Jabra UC VOICE 750a Mono MS
* Lenovo Pro Wired Stereo VoIP Headset
* Mitel Evolve 75
* Mitel S720
* NXT Technologies HUB 
* NXT Technologies UC-2000 Stereo Headset
* NXT Technologies UC-5100 
* NXT Technologies UC-7500 Mono
* NXT Technologies UC-7500 Stereo
* USB2 Jabra Engage 75

**Comment by Nederby** [comment]
Thanks 👍

**Comment by Nederby** [comment]
Hi again, 

What devices are supported in v3 - still the same as above?

Thanks in advance!

**Comment by JabraDIME** [comment]
hi, we are now recommending the following products for the best SDK experience:
 
[Integrating Jabra.pdf](https://github.com/gnaudio/jabra-node-sdk/files/4576543/Integrating.Jabra.pdf)

**Comment by Nederby** [comment]
Thanks!
