### ISSUE TITLE
Undocking emits btnPress twice

### ISSUE THREAD

**Issue by amedvedsy** [gnaudio/jabra-node-sdk#6]
NodeJs v8.16.1
Electron 2.0.18
jabra-node-sdk 2.0.0-beta.2
**Device Jabra Pro 9470**

When I undock headphones
Expect btnPress is emitted with btn type 1 and value true

Current behaviour:
btnPress is emitted with btn type 1 and value true
after few seconds btnPress is emitted again with btn type 1 and value false

Same issue happens when I use multifunctional button
I click on button 
btnPress is emitted with btn type 1 and value true
after few seconds btnPress is emitted again with btn type 1 and value false

**Comment by extmchristensen** [comment]
Which protocol are you using HI or GN_HID (see FAQ for details) ?

If setting the right protocol does not fix you issue, please submit a reproducible sample script that outputs the events (you can look at one of the [standard examples](https://github.com/gnaudio/jabra-node-sdk/blob/master/nodesdk/src/example/example1b.ts) for inspiration

**Comment by amedvedsy** [comment]
@extmchristensen ,
```
        j.createJabraApplication(config.get('jabraAppKey'))
            .then((jabra) => {
                jabra.on('attach', (device) => {
                    console.log('Press any key on Jabra device ' + device.deviceName);

                    // If you are creating a softphone, consider using GN protocol when device supports it
                    // in order to receive all events. E.g. device.setHidWorkingStateAsync(j.enumHidState.GN_HID);

                    console.log(j.enumHidState.GN_HID);

                    device.setHidWorkingStateAsync(j.enumHidState.GN_HID)
                        .then(() => {
                            device.on('btnPress', (btnType, btnValue) => {
                                console.log('New input from device is received: ', btnType, btnValue);
                            });
                        })
                });
            });
```

When I undock headphones, output is 
New input from device is received:  1 true
New input from device is received:  1 false (this one appears in 2sec after previous)

**Comment by extmchristensen** [comment]
When you get such events, they should be considered as requests that you must follow through with an action. In this case, you should issue a offhookAsync() command after receiving the Offhook btnType. Please check if that works for you and report back.

**Comment by amedvedsy** [comment]
It works, thanks
