### ISSUE TITLE
Undocking doesn't emit btnPress event

### ISSUE THREAD

**Issue by amedvedsy** [gnaudio/jabra-node-sdk#7]
NodeJs v8.16.1
Electron 2.0.18
jabra-node-sdk 2.0.0-beta.2
**Device Jabra Engage 75**

**Undock headphones**
btnPress is not emitted
**Press multifunctional button** 
btnPress is triggered 3 times
24 true
21 true
18 true
**Press multifunctional button**
btnPress is triggered 3 times
24 false
21 false
18 false
**Press multifunctional button** 
btnPress is triggered 3 times
24 true
21 true
18 true
**Dock headphones**
btnPress is triggered 3 times
24 false
21 false
18 false
**Undock headphones**
btnPress is not emitted

I think btnPress should be emitted when I undock headphones

**Comment by extmchristensen** [comment]
Which protocol are you using HI or GN_HID (see FAQ for details) ?

If setting the right protocol does not fix you issue, please submit a reproducible sample script that outputs the events (you can look at one of the [standard examples](https://github.com/gnaudio/jabra-node-sdk/blob/master/nodesdk/src/example/example1b.ts) for inspiration

**Comment by amedvedsy** [comment]
@extmchristensen , 
        ```
j.createJabraApplication(config.get('jabraAppKey'))
            .then((jabra) => {
                jabra.on('attach', (device) => {
                    console.log('Press any key on Jabra device ' + device.deviceName);

                    // If you are creating a softphone, consider using GN protocol when device supports it
                    // in order to receive all events. E.g. device.setHidWorkingStateAsync(j.enumHidState.GN_HID);

                    console.log(j.enumHidState.GN_HID);

                    device.setHidWorkingStateAsync(j.enumHidState.GN_HID)
                        .then(() => {
                            device.on('btnPress', (btnType, btnValue) => {
                                console.log('New input from device is received: ', btnType, btnValue);
                            });
                        })
                });
            });
```

Undocking doesn't emit event

**Comment by extmchristensen** [comment]
Note sure what you mean with undock for Engage 75 ?

**Comment by amedvedsy** [comment]
I mean taking up headphones from base

**Comment by extvpadmanabhan** [comment]
@amedvedsy 
I tried Undocking the headphones from the base and I am getting the btnPress events properly.

Please Note: 

To get the btnPress event fired on undocking the headphones,
"Open softphone line when undocking headset" setting under Softphone(PC) group has to be enabled on the device.
(This setting will be disabled by default)
Without which Undocking will not have any kind of change on the audio link of the device.

For enabling this settings, you can use 
	a. Jabra Direct application from [jabra-direct-app](https://www.jabra.in/software-and-services/jabra-direct)
		or 
	b. call setSettingsAsync API from jabra-node-sdk module.

If the setting is enabled and you are not able to get the event, please try below things:
1.	Restore the device to default settings and enable the above setting again and check Undock scenario.
2.	Try Firmware Update on the device.

please let me know if this solves the issue

**Comment by extvpadmanabhan** [comment]
The btnPress event is triggered 3 times as they are 
btnCode :      btnType

24  : PseudoOffHook
21  : LineBusy
18  : Online

These are three different events and it will be emitted on all offhook and onhook events as they change the audio link on the device.
